#!/usr/bin/env bash
# Auto-generated by heimdall scripts/install_petclinic_override.sh
# 用法：
#   bash .heimdall.sh up                       # 启动全部并叠加 heimdall 注入
#   bash .heimdall.sh up prometheus-server     # 仅重启 prometheus-server
#   bash .heimdall.sh ps                       # 查看
#   bash .heimdall.sh logs prometheus-server   # 看 prom 日志
#   bash .heimdall.sh down                     # 停止
# 任何其他子命令（restart/build/exec/config/...）均透传给 docker compose。
set -euo pipefail
cd "$(dirname "$0")"

cmd="${1:-up}"; shift || true

# 三层叠加: 原 compose + PetClinic 自己的 sidecar overlay + heimdall prom 注入
DC=(docker compose
    -f docker-compose.yml
    -f docker-compose.override.yml
    -f "/Users/chensheng/heimdall/deploy/petclinic-bridge/docker-compose.heimdall-prom.yml")

case "$cmd" in
    up)    exec "${DC[@]}" up -d "$@" ;;
    down)  exec "${DC[@]}" down "$@" ;;
    ps)    exec "${DC[@]}" ps "$@" ;;
    logs)  exec "${DC[@]}" logs --tail 200 "$@" ;;
    *)     exec "${DC[@]}" "$cmd" "$@" ;;
esac
